import * as Speech from 'expo-speech';
import { Audio } from 'expo-av';

// Metro bundler requires static paths — no dynamic require() allowed.
// Add an entry here for every file generated by scripts/generate_phonemes.py.
const PHONEME_AUDIO: Record<string, number> = {
  s:  require('../../assets/sounds/phonemes/s.mp3'),
  a:  require('../../assets/sounds/phonemes/a.mp3'),
  t:  require('../../assets/sounds/phonemes/t.mp3'),
  p:  require('../../assets/sounds/phonemes/p.mp3'),
  m:  require('../../assets/sounds/phonemes/m.mp3'),
  i:  require('../../assets/sounds/phonemes/i.mp3'),
  d:  require('../../assets/sounds/phonemes/d.mp3'),
  n:  require('../../assets/sounds/phonemes/n.mp3'),
  g:  require('../../assets/sounds/phonemes/g.mp3'),
  o:  require('../../assets/sounds/phonemes/o.mp3'),
  c:  require('../../assets/sounds/phonemes/c.mp3'),
  k:  require('../../assets/sounds/phonemes/k.mp3'),
  e:  require('../../assets/sounds/phonemes/e.mp3'),
  r:  require('../../assets/sounds/phonemes/r.mp3'),
  u:  require('../../assets/sounds/phonemes/u.mp3'),
  l:  require('../../assets/sounds/phonemes/l.mp3'),
  h:  require('../../assets/sounds/phonemes/h.mp3'),
  f:  require('../../assets/sounds/phonemes/f.mp3'),
  b:  require('../../assets/sounds/phonemes/b.mp3'),
  sh: require('../../assets/sounds/phonemes/sh.mp3'),
  ch: require('../../assets/sounds/phonemes/ch.mp3'),
  th: require('../../assets/sounds/phonemes/th.mp3'),
  wh: require('../../assets/sounds/phonemes/wh.mp3'),
  ck: require('../../assets/sounds/phonemes/ck.mp3'),
  ll: require('../../assets/sounds/phonemes/ll.mp3'),
  ss: require('../../assets/sounds/phonemes/ss.mp3'),
  ff: require('../../assets/sounds/phonemes/ff.mp3'),
  w:  require('../../assets/sounds/phonemes/w.mp3'),
  v:  require('../../assets/sounds/phonemes/v.mp3'),
  y:  require('../../assets/sounds/phonemes/y.mp3'),
  z:  require('../../assets/sounds/phonemes/z.mp3'),
  x:  require('../../assets/sounds/phonemes/x.mp3'),
};

let _currentSound: Audio.Sound | null = null;

/**
 * Play the phoneme sound for a letter.
 * Uses a pre-recorded MP3 (IPA-accurate) when available; falls back to TTS.
 * letterId is the letter's id field, e.g. 'S', 'SH', 'A'.
 */
export const playLetterSound = async (letterId: string, fallbackSound: string): Promise<void> => {
  // Unload any previous sound to avoid overlapping playback
  if (_currentSound) {
    await _currentSound.unloadAsync().catch(() => {});
    _currentSound = null;
  }

  const key = letterId.toLowerCase();
  const audioFile = PHONEME_AUDIO[key];

  if (audioFile) {
    try {
      const { sound } = await Audio.Sound.createAsync(audioFile, { shouldPlay: true });
      _currentSound = sound;
      sound.setOnPlaybackStatusUpdate((status) => {
        if (status.isLoaded && status.didJustFinish) {
          sound.unloadAsync();
          if (_currentSound === sound) _currentSound = null;
        }
      });
      return;
    } catch (err) {
      console.warn(`Audio file failed for "${key}", falling back to TTS:`, err);
    }
  }

  // TTS fallback (used before files are generated or if a file fails)
  try {
    await Speech.stop();
    await Speech.speak(fallbackSound, {
      language: 'en-US',
      pitch: 1.1,
      rate: 0.6,
    });
  } catch (error) {
    console.error('TTS error:', error);
  }
};

export const getLetterColor = (letter: string, defaultColor?: string): string => {
  if (defaultColor) return defaultColor;

  const colors = [
    '#FF6B6B', '#FFD93D', '#6BCB77', '#4D96FF',
    '#BB86FC', '#FF9D5C', '#FF6BB9', '#1ABC9C',
    '#3498DB', '#E74C3C',
  ];

  return colors[letter.charCodeAt(0) % colors.length];
};

export const formatPhaseName = (phase: number, name: string): string => {
  return name || `Phase ${phase}`;
};

export const calculateProgress = (learned: number, total: number): number => {
  if (total === 0) return 0;
  return Math.round((learned / total) * 100);
};
